%% Author_tex.tex
%% V1.0
%% 2012/13/12
%% developed by Techset
%%
%% This file describes the coding for modeloUFCG.cls

\documentclass[a4paper]{modeloUFCG} %%%% where modeloUFCG is the template name

\usepackage[portuguese]{babel}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{fancyhdr}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{calc}
%% Fixa cada figura exatamente onde e gerada ([H]). Sem isso, floats podem
%% "flutuar" livremente e, neste documento (muitas figuras grandes em
%% sequencia), acabam se deslocando para muito longe do texto que os
%% referencia -- inclusive interferindo na quebra de pagina de tabelas
%% longtable vizinhas.
\usepackage{float}

%% A classe modeloUFCG.cls calcula largura/altura de texto e margens
%% assumindo o formato de trim de um periodico (174mm x 247mm), mas o PDF
%% final e produzido em A4 (210mm x 297mm). Isso deixa sobras enormes nas
%% margens. O pacote geometry forca margens A4 corretas, sobrepondo o
%% calculo original da classe.
\usepackage[a4paper, margin=2.5cm]{geometry}

\pagestyle{fancy}
\renewcommand{\headrulewidth}{0pt}
\fancyhead[L]{}
\fancyhead[C]{}
\fancyhead[R]{}

%% A classe usa \flushbottom, que estica os espacos em branco de cada pagina
%% para preenche-la ate o final. Combinado com figuras fixas ([H]), isso cria
%% buracos enormes entre uma figura/tabela e o texto seguinte. \raggedbottom
%% deixa o espaco sobrando apenas no rodape da pagina, sem esticar o meio.
\raggedbottom

%% Espacamento mais enxuto ao redor de figuras e tabelas.
\setlength{\floatsep}{8pt plus 2pt minus 2pt}
\setlength{\textfloatsep}{10pt plus 2pt minus 2pt}
\setlength{\intextsep}{8pt plus 2pt minus 2pt}


%%%% *** Do not adjust lengths that control margins, column widths, etc. ***

%%%%%%%%%%% Defining Enunciations  %%%%%%%%%%%
\newtheorem{theorem}{\bf Teorema}[section]
\newtheorem{condition}{\bf Condição}[section]
\newtheorem{corollary}{\bf Corolário}[section]
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\usepackage{titlesec}
\renewcommand{\thesection}{\arabic{section}}
\renewcommand{\thesubsection}{\thesection.\arabic{subsection}}
\renewcommand{\thesubsubsection}{\thesubsection.\arabic{subsubsection}}

%%%% Cabecalho no estilo de artigo academico, substituindo a capa           %%%%
%%%% original (logo + caixa de titulo) do template Royal Society.          %%%%
%%%% A caixa de resumo estreita e trocada por um resumo de largura total,  %%%%
%%%% exibido logo apos o titulo/autores, como em um artigo convencional.   %%%%
%% Apos o \documentclass terminar de carregar, o LaTeX restaura o catcode de
%% @ para "outro", entao qualquer referencia a comandos internos da classe
%% (\@title, \@author, \if@subject@provided etc.) precisa ficar dentro de
%% \makeatletter ... \makeatother para ser reconhecida corretamente.
\makeatletter

%% Centraliza as legendas de figuras e tabelas (a classe original as deixa
%% alinhadas a esquerda).
\long\def\@makecaption#1#2{%
  \vskip\abovecaptionskip
  \centering{\captionheadfont #1.}\hskip2.5pt{\captionfont #2}\par
  \vskip\belowcaptionskip}

\renewenvironment{abstract}{%
  \global\setbox\absbox\vbox\bgroup\par\abstractfont
  \leftskip0pc\rightskip0pc\noindent\ignorespaces
}{\par\egroup}

%% A classe modeloUFCG.cls define \@maketitle atraves de mecanismos internos
%% (fila de duas colunas / bloco de revisao editorial) que absorvem qualquer
%% redefinicao de \@maketitle sem executa-la. Para evitar essa maquinaria,
%% \maketitle e redefinido diretamente aqui.
\renewcommand\maketitle{%
  \vspace*{-2.2cm}
  \noindent\begin{minipage}[c]{2.2cm}
    \includegraphics[width=2cm]{lea_logo_bw}
  \end{minipage}%
  \begin{minipage}[c]{\textwidth-2.2cm}
    {\fontfamily{\sfdefault}\fontseries{b}\fontshape{n}\fontsize{12}{14}\selectfont
      UNIVERSIDADE FEDERAL DE CAMPINA GRANDE\par}
          {\fontfamily{\sfdefault}\fontseries{m}\fontshape{n}\fontsize{11}{13}\selectfont
       Disciplina: Estatística Aplicada%
        \quad---\quad Período: 2026.1\par}
              {\fontfamily{\sfdefault}\fontseries{m}\fontshape{n}\fontsize{11}{13}\selectfont
       Professores: Profa. Dra. Amanda Gomes; Prof.~Dr.~Jerfson Bruno; Prof.~Dr.~Gilberto Matos\par}
      \end{minipage}
  \vskip4pt
  \rule{\textwidth}{.5pt}
  \vskip8pt
  \begin{center}
    {\fontfamily{\sfdefault}\fontseries{m}\fontshape{n}\fontsize{16}{18}\selectfont\mathversion{bold}\@title\par}
    \vskip6pt
    {\authorfont\@author\par}
    \vskip3pt
    \ifx\@address\empty\else
      {\addressfont\@address\par}
    \fi
    \vskip6pt
    \rule{\textwidth}{.5pt}
  \end{center}
  \vskip8pt
  \ifvoid\absbox\else
    {\fontfamily{\sfdefault}\fontseries{b}\fontshape{n}\fontsize{11}{13}\selectfont Resumo}\par
    \vskip4pt
    \noindent\usebox\absbox\par
    \vskip6pt
  \fi
  \if@subject@provided
    {\subjectfont\@subject\par}
    \vskip4pt
  \fi
  \if@keywords@provided
    {\keywordfont\@keywords\par}
  \fi
  \vskip10pt
}

\makeatother

\begin{document}

%%%% Article title to be placed here
\title{Estatísticas de criminalidade violenta por estado americano (por 100 mil habitantes): assassinatos, assaltos e estupros, além do percentual da população urbana.}

\author{
Stefany Nicole Santos Alves$^{a}$}

\address{
  $^{a}$Departamento de Ciência da Computação - UFCG}
%%%% Subject entries to be placed here %%%%
\subject{
estatistica aplicada,
modelagem preditiva}

%%%% Keyword entries to be placed here %%%%
\keywords{
regressao linear multipla,
selecao de modelos,
diagnostico de residuos,
usarrests}

%%%% Abstract text to be placed here %%%%%%%%%%%%
\begin{abstract}
Este trabalho aplica a metodologia de regressão linear múltipla (MRLM) ao conjunto de dados USArrests, contendo estatísticas de criminalidade violenta por estado americano em 1973. O objetivo é modelar o número de prisões por assalto a partir das taxas de assassinato, estupro e percentual de população urbana. Realizamos uma análise exploratória, ajustamos um modelo inicial com todas as variáveis explicativas contínuas e verificamos a ausência de multicolinearidade severa, diferentemente de outros cenários clássicos. Comparamos modelos candidatos por critério de Akaike (AIC) e selecionamos um modelo final parcimonioso e estatisticamente significante. Verificamos os pressupostos desse modelo através de análise de resíduos, gráfico de envelope simulado e identificação de pontos atípicos, de alavanca e influentes. Por fim, apresentamos os intervalos de confiança para o valor médio esperado da variável resposta e os intervalos de predição para novas observações.
\end{abstract}
%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Some pieces required from the pandoc template
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\providecommand{\EndFirstPage}{%
}

\maketitle

\section{Introdução}\label{introduuxe7uxe3o}

A criminalidade é um tema importante para a análise de dados, pois diferentes fatores podem estar relacionados aos índices de violência. A base de dados utilizada
neste trabalho, \textbf{USArrests}, reúne informações dos 50 estados americanos referentes ao ano de 1973. Ela contém o número de \textbf{prisões por assassinato} (\texttt{Murder}),
\textbf{assalto} (\texttt{Assault}) e \textbf{estupro} (\texttt{Rape}), por 100 mil habitantes, além do percentual da população que vive em áreas urbanas (\texttt{UrbanPop}).

Neste trabalho, o objetivo é modelar o número de \textbf{prisões por assalto} (\texttt{Assault}) a partir das demais variáveis da base. Esse problema é interessante porque permite
analisar como diferentes tipos de crimes e o nível de urbanização estão relacionados com a variável resposta, além de aplicar técnicas de regressão linear múltipla.

Especificamente, buscamos:
(i) descrever a base de dados e realizar uma análise exploratória;
(ii) ajustar um modelo inicial de regressão linear múltipla;
(iii) avaliar a presença de multicolinearidade e selecionar um modelo mais adequado;
(iv) verificar os pressupostos do modelo; e
(v) interpretar os resultados obtidos.

\section{Metodologia}\label{metodologia}

Os dados correspondem aos 50 estados americanos no ano de 1973, sem valores ausentes, contendo quatro variáveis numéricas: \texttt{Murder}, \texttt{Assault}, \texttt{UrbanPop} e \texttt{Rape}.
A análise exploratória compreendeu estatísticas descritivas, matriz de correlação, histogramas, boxplots e matriz de dispersão entre as variáveis.

\subsection{Modelo de regressão linear múltipla}\label{modelo-de-regressuxe3o-linear-muxfaltipla}

Seja \(y_i\) o número de \textbf{prisões por assalto} da \(i\)-ésima observação (estado). O modelo inicial, utilizando todas as demais variáveis da base como explicativas, é dado por

\[
y_i = \beta_0 + \beta_1,\text{Murder}_i + \beta_2,\text{UrbanPop}_i + \beta_3,\text{Rape}_i + \varepsilon_i,
\]

\noindent em que \(\varepsilon_i\) segue as suposições usuais do Modelo de Regressão Linear Múltipla (MRLM) \cite{Kutner2004}: média nula, variância constante,
independência e normalidade.

A multicolinearidade entre as variáveis explicativas foi avaliada por dois critérios complementares: (a) a matriz de correlações entre as variáveis preditoras,
em que valores absolutos de correlação maiores que 0,8 indicam possível multicolinearidade; e (b) o fator de inflação da variância (VIF), dado por
\(\text{VIF}_j = 1/(1-R_j^2)\), em que \(R_j^2\) é o coeficiente de determinação da regressão de \(X_j\) sobre as demais variáveis explicativas. Valores de \(\text{VIF}\)
superiores a 5 indicam possível problema de multicolinearidade, enquanto valores acima de 10 sugerem multicolinearidade severa \cite{Kutner2004}.

A seleção do modelo foi realizada utilizando os critérios de informação de Akaike (AIC) \cite{Akaike1974} e Bayesiano (BIC) \cite{Schwarz1978}, além do teste
\(F\) para comparação entre modelos aninhados. Em ambos os critérios de informação, modelos com menores valores de AIC e BIC são preferíveis. Como apoio à seleção,
também foi utilizado o procedimento automático \emph{stepwise} (\texttt{step}), baseado no critério AIC, permitindo comparar a seleção automática com a escolha baseada na interpretação
estatística dos resultados.

\subsection{Diagnóstico do modelo}\label{diagnuxf3stico-do-modelo}

A adequação do modelo selecionado foi avaliada por meio da análise gráfica dos resíduos, utilizando os gráficos de resíduos versus valores ajustados, quantil-quantil
(Q-Q Plot), escala-localização e resíduos versus alavancagem. Esses gráficos permitem verificar os principais pressupostos do Modelo de Regressão Linear Múltipla,
como linearidade, homocedasticidade, normalidade dos resíduos e a presença de observações influentes \cite{Kutner2004}.

Também foram analisadas possíveis observações atípicas, de alavanca e influentes utilizando os resíduos studentizados (\(|t_i| > 2\)), os valores de alavancagem
(\(h_{ii} > 2p/n\)) e a distância de Cook (\(D_i > 4/n\)) \cite{Cook1977,CookWeisberg1982,Kutner2004}. Caso fossem identificadas observações com influência significativa
sobre o ajuste, seria avaliado o impacto de sua remoção por meio do reajuste do modelo.

Por fim, para facilitar a comparação da influência das variáveis explicativas, foram calculados os coeficientes padronizados do modelo final. Como as variáveis estão em
escalas diferentes, essa padronização permite comparar diretamente a contribuição relativa de cada variável para explicar o número de prisões por assalto.

\subsection{Variáveis explicativas}\label{variuxe1veis-explicativas}

Diferentemente de outros conjuntos de dados que possuem variáveis categóricas, a base \textbf{USArrests} é composta apenas por variáveis numéricas (\texttt{Murder}, \texttt{UrbanPop} e \texttt{Rape}),
utilizadas como variáveis explicativas do modelo. Dessa forma, não foi necessária a criação de variáveis \emph{dummy} nem a definição de uma categoria de referência.
O modelo foi ajustado diretamente utilizando essas variáveis contínuas para explicar o número de prisões por assalto (\texttt{Assault}).

\subsection{Inferência preditiva}\label{inferuxeancia-preditiva}

Para um conjunto de valores das variáveis explicativas (\texttt{Murder}, \texttt{UrbanPop} e \texttt{Rape}), é possível realizar dois tipos de inferência \cite{Kutner2004}:
o \textbf{intervalo de confiança} para o valor médio esperado de prisões por assalto, que estima a média da resposta para estados com essas características, e
o \textbf{intervalo de predição} para uma \textbf{nova observação}, que estima um valor futuro de prisões por assalto para um estado com as mesmas características.
Como o intervalo de predição considera também a variabilidade entre observações individuais, ele é naturalmente mais amplo que o intervalo de confiança.
Ambos foram calculados para dois conjuntos hipotéticos de valores das variáveis explicativas, escolhidos dentro do intervalo observado na base de dados.

\section{Resultados}\label{resultados}

\subsection{Descrição da base de dados}\label{descriuxe7uxe3o-da-base-de-dados}

A base \texttt{USArrests} possui \(n = 50\) observações, correspondentes aos 50 estados americanos, e 4 variáveis numéricas (Tabela \ref{tab:variaveis}), sem valores ausentes.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.0900}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.6400}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.2700}}@{}}
\caption{\label{tab:variaveis} Variáveis da base de dados \protect\texttt{USArrests}, descrição e unidade de medida.}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Variável
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Descrição
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Unidade
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Variável
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Descrição
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Unidade
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Murder & Prisões por assassinato (por 100 mil habitantes) & prisões/100 mil habitantes \\
Assault & Prisões por assalto (variável resposta, por 100 mil habitantes) & prisões/100 mil habitantes \\
UrbanPop & Percentual da população urbana & \% \\
Rape & Prisões por estupro (por 100 mil habitantes) & prisões/100 mil habitantes \\
\end{longtable}

\subsection{Análise exploratória}\label{anuxe1lise-exploratuxf3ria}

A Tabela \ref{tab:descritivas} apresenta as estatísticas descritivas das variáveis da base \texttt{USArrests}.

\begin{longtable}[]{@{}llrr@{}}
\caption{\label{tab:descritivas}\label{tab:descritivas} Média e desvio-padrão (dp) das variáveis da base USArrests.}\tabularnewline
\toprule\noalign{}
& Variável & Média & Desvio.padrão \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
& Variável & Média & Desvio.padrão \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Murder & Murder & 7.79 & 4.36 \\
Assault & Assault & 170.76 & 83.34 \\
UrbanPop & UrbanPop & 65.54 & 14.47 \\
Rape & Rape & 21.23 & 9.37 \\
\end{longtable}

A Figura \ref{fig:boxplots} apresenta os box-plots das variáveis da base. Observa-se que \texttt{Assault} e \texttt{Rape} apresentam maior dispersão dos dados, enquanto \texttt{UrbanPop} possui distribuição mais concentrada. Além disso, algumas variáveis apresentam observações mais afastadas da maior parte dos dados, indicando possíveis valores extremos.

\begin{figure}[H]

{\centering \includegraphics[width=1\linewidth]{relatorio_files/figure-latex/boxplots-1} 

}

\caption{\label{fig:boxplots} Box-plots das variáveis da base USArrests.}\label{fig:boxplots}
\end{figure}

\subsubsection{Análise de correlação}\label{anuxe1lise-de-correlauxe7uxe3o}

A Figura \ref{fig:corrplot} exibe a matriz de correlações entre as variáveis da base \texttt{USArrests}, e a Figura \ref{fig:ggpairs} apresenta a matriz de dispersão par a par.

\begin{figure}[H]

{\centering \includegraphics[width=0.65\linewidth]{relatorio_files/figure-latex/corrplot-1} 

}

\caption{\label{fig:corrplot} Matriz de correlações entre as variáveis da base USArrests.}\label{fig:corrplot}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=1\linewidth]{relatorio_files/figure-latex/ggpairs-1} 

}

\caption{\label{fig:ggpairs} Matriz de dispersão par a par das variáveis da base USArrests.}\label{fig:ggpairs}
\end{figure}

Com relação à análise de correlação, é desejável observar altas correlações das variáveis explicativas com a variável resposta \texttt{Assault}, mas correlações elevadas \emph{entre} as próprias variáveis explicativas podem indicar multicolinearidade. Como regra geral, correlações absolutas iguais ou superiores a \(0{,}8\) constituem um indício importante desse problema. Examinando a Figura \ref{fig:corrplot} em detalhe:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  A variável resposta \texttt{Assault}:

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    apresenta correlação linear forte e positiva com \texttt{Murder} (\(r = 0{,}80\));
  \item
    apresenta correlação linear fraca e positiva com \texttt{UrbanPop} (\(r = 0{,}26\));
  \item
    apresenta correlação linear moderada e positiva com \texttt{Rape} (\(r = 0{,}66\)).
  \end{enumerate}
\item
  Entre as variáveis explicativas, \texttt{Murder} correlaciona-se de forma moderada e positiva com \texttt{Rape} (\(r = 0{,}56\)), enquanto as correlações envolvendo \texttt{UrbanPop} apresentam baixa magnitude. Como nenhuma dessas correlações ultrapassa, em valor absoluto, o limiar de \(0{,}8\), elas não configuram, isoladamente, um indício forte de multicolinearidade.
\item
  A análise da matriz de correlação sugere que as variáveis explicativas não apresentam correlações suficientemente elevadas para indicar multicolinearidade severa. Essa conclusão será complementada pela análise do fator de inflação da variância (VIF), apresentada na próxima seção.
\end{enumerate}

\subsubsection{Multicolinearidade: o VIF}\label{multicolinearidade-o-vif}

Para avaliar formalmente a possível multicolinearidade sugerida pela análise de correlação, ajustamos um modelo inicial utilizando \texttt{Assault} como variável resposta e \texttt{Murder}, \texttt{UrbanPop} e \texttt{Rape} como variáveis explicativas. Em seguida, calculamos o fator de inflação da variância (VIF) de cada variável (Tabela \ref{tab:vifCompleto}).

\begin{longtable}[]{@{}lrrrr@{}}
\caption{\label{tab:coefInicial} Estimativas dos coeficientes do modelo inicial.}\tabularnewline
\toprule\noalign{}
Termo & Estimativa & Erro Padrão & Estatística t & p-valor \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Termo & Estimativa & Erro Padrão & Estatística t & p-valor \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Intercepto & -15.4520 & 31.8581 & -0.4850 & 0.6300 \\
Murder & 12.4700 & 1.8533 & 6.7286 & 0.0000 \\
UrbanPop & 0.6304 & 0.5054 & 1.2474 & 0.2186 \\
Rape & 2.2502 & 0.9432 & 2.3857 & 0.0212 \\
\end{longtable}

\begin{longtable}[]{@{}lr@{}}
\caption{\label{tab:vifCompleto} Fator de inflação de variância (VIF) de cada variável explicativa no modelo inicial.}\tabularnewline
\toprule\noalign{}
Variável & VIF \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Variável & VIF \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Murder & 1.54 \\
UrbanPop & 1.26 \\
Rape & 1.84 \\
\end{longtable}

O modelo inicial apresenta coeficiente de determinação ajustado igual a \(R^2_{aj} = 0.7009\). Observando a Tabela \ref{tab:coefInicial}, verifica-se que as variáveis \texttt{Murder} e \texttt{Rape} são estatisticamente significativas, enquanto \texttt{UrbanPop} não apresenta evidências suficientes de associação com a variável resposta ao nível de significância de 5\%.

Com relação à multicolinearidade, a Tabela \ref{tab:vifCompleto} mostra que todas as variáveis explicativas apresentam valores de VIF inferiores ao limite de referência de 5, sendo o maior valor igual a 1.84. Esses resultados indicam que não há evidências de multicolinearidade relevante entre as variáveis explicativas, confirmando a conclusão obtida anteriormente por meio da análise da matriz de correlação.

Assim, a presença de multicolinearidade não constitui um problema para o ajuste do modelo, permitindo que a seleção do modelo final seja baseada principalmente na significância estatística das variáveis e nos critérios de comparação entre modelos.

\subsection{Seleção do modelo final}\label{seleuxe7uxe3o-do-modelo-final}

Como a variável \texttt{UrbanPop} não apresentou significância estatística no modelo inicial, ajustamos um segundo modelo removendo essa variável e comparamos os dois modelos por meio do coeficiente de determinação ajustado, dos critérios AIC e BIC (Tabela \ref{tab:selecaoModelos}).

\begin{longtable}[]{@{}lrrr@{}}
\caption{\label{tab:selecaoModelos} Comparação dos modelos candidatos: ajuste, AIC e BIC.}\tabularnewline
\toprule\noalign{}
Modelo & R² ajustado & AIC & BIC \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Modelo & R² ajustado & AIC & BIC \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
modelo1 (completo) & 0.7009 & 529.67 & 539.23 \\
modelo2 (sem UrbanPop) & 0.6973 & 529.33 & 536.98 \\
\end{longtable}

Observa-se que o modelo2 apresenta valores de AIC e BIC menores que o modelo completo, além de manter praticamente o mesmo coeficiente de determinação ajustado. Esses resultados indicam que a remoção de \texttt{UrbanPop} torna o modelo mais parcimonioso, sem perda significativa de qualidade no ajuste.

Para verificar formalmente se a retirada da variável compromete o ajuste do modelo, realizamos um teste F comparando os dois modelos.

\begin{longtable}[]{@{}lrrllll@{}}
\caption{\label{tab:anovaModelo2} Teste F comparando o modelo2 ao modelo completo (modelo1).}\tabularnewline
\toprule\noalign{}
Modelo & GL Res. & SQ Res. & GL & SQ & Estatística F & p-valor \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Modelo & GL Res. & SQ Res. & GL & SQ & Estatística F & p-valor \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
modelo2 & 47 & 98796.73 & & & & \\
modelo1 & 46 & 95564.05 & 1 & 3232.68 & 1.5561 & 0.2186 \\
\end{longtable}

O teste F apresentou valor de \(p = 0.2186\), indicando que não há evidências suficientes para rejeitar a hipótese nula de que o modelo reduzido explica os dados tão bem quanto o modelo completo.

\begin{longtable}[]{@{}lrrrr@{}}
\caption{\label{tab:coefModelo2} Estimativas dos coeficientes do modelo selecionado (modelo2).}\tabularnewline
\toprule\noalign{}
Termo & Estimativa & Erro Padrão & Estatística t & p-valor \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Termo & Estimativa & Erro Padrão & Estatística t & p-valor \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Intercepto & 18.4663 & 16.6993 & 1.1058 & 0.2744 \\
Murder & 11.9719 & 1.8204 & 6.5764 & 0.0000 \\
Rape & 2.7815 & 0.8465 & 3.2858 & 0.0019 \\
\end{longtable}

\subsection{Diagnóstico do modelo selecionado}\label{diagnuxf3stico-do-modelo-selecionado}

A Tabela \ref{tab:coefModelo2} apresenta as estimativas dos coeficientes do modelo selecionado (\texttt{modelo2}), utilizado para verificar os pressupostos da regressão linear múltipla.

\begin{longtable}[]{@{}lrrrr@{}}
\caption{\label{tab:coefModelo2} Estimativas dos coeficientes do modelo2 (modelo selecionado).}\tabularnewline
\toprule\noalign{}
Termo & Estimativa & Erro Padrão & Estatística t & p-valor \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Termo & Estimativa & Erro Padrão & Estatística t & p-valor \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Intercepto & 18.4663 & 16.6993 & 1.1058 & 0.2744 \\
Murder & 11.9719 & 1.8204 & 6.5764 & 0.0000 \\
Rape & 2.7815 & 0.8465 & 3.2858 & 0.0019 \\
\end{longtable}

\begin{figure}[H]

{\centering \includegraphics[width=1\linewidth]{relatorio_files/figure-latex/diagnosticoModelo2-1} 

}

\caption{Análise de resíduos do modelo2.}\label{fig:diagnosticoModelo2}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.65\linewidth]{relatorio_files/figure-latex/envelopeModelo2-1} 

}

\caption{Gráfico de envelope simulado do modelo2.}\label{fig:envelopeModelo2}
\end{figure}

As Figuras \ref{fig:diagnosticoModelo2} e \ref{fig:envelopeModelo2} foram utilizadas para avaliar os pressupostos do modelo de regressão. O gráfico de resíduos versus valores ajustados permite verificar a linearidade e a homocedasticidade, enquanto o gráfico quantil-quantil (QQ-plot) e o envelope simulado auxiliam na avaliação da normalidade dos resíduos.

Não sendo observados padrões sistemáticos nos resíduos e permanecendo a maior parte das observações dentro da banda do envelope simulado, considera-se que as suposições de linearidade, variância constante e normalidade dos erros são razoavelmente atendidas. Dessa forma, o modelo selecionado mostra-se adequado para explicar a relação entre as variáveis \texttt{Murder} e \texttt{Rape} e a variável resposta \texttt{Assault}.

\subsubsection{Identificação de pontos atípicos, de alavanca e influentes}\label{identificauxe7uxe3o-de-pontos-atuxedpicos-de-alavanca-e-influentes}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1807}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1807}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1446}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1687}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0964}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1084}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1205}}@{}}
\caption{\label{tab:pontosInfluentes} Observações atípicas, de alavanca e/ou influentes segundo o modelo2.}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Estado
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Resíduo estud.
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Alavancagem
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Dist. de Cook
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Atípico
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Alavanca
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Influente
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Estado
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Resíduo estud.
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Alavancagem
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Dist. de Cook
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Atípico
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Alavanca
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Influente
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
North Carolina & 2.91 & 0.094 & 0.2531 & Sim & Não & Sim \\
Georgia & -2.13 & 0.136 & 0.2224 & Sim & Sim & Sim \\
Rhode Island & 2.14 & 0.060 & 0.0914 & Sim & Não & Sim \\
Arizona & 2.14 & 0.050 & 0.0752 & Sim & Não & Não \\
Nevada & -0.97 & 0.170 & 0.0638 & Não & Sim & Não \\
Delaware & 2.44 & 0.027 & 0.0502 & Sim & Não & Não \\
Hawaii & -2.11 & 0.028 & 0.0399 & Sim & Não & Não \\
California & 0.86 & 0.131 & 0.0373 & Não & Sim & Não \\
Colorado & -0.39 & 0.122 & 0.0070 & Não & Sim & Não \\
Alaska & 0.02 & 0.170 & 0.0000 & Não & Sim & Não \\
Mississippi & 0.01 & 0.163 & 0.0000 & Não & Sim & Não \\
\end{longtable}

Com \(n = 50\) observações e \(p = 3\) parâmetros, o limiar de alavancagem é \(2p/n \approx 0.12\) e o de influência (Cook) é \(4/n \approx 0.08\). Ao todo, 11 observações (22\%) violam pelo menos um dos critérios, e 3 são influentes segundo a distância de Cook.

Como as observações identificadas correspondem a estados reais da base \texttt{USArrests}, não há evidências de erro de registro que justifiquem sua remoção. Assim, o modelo é mantido com todas as observações, preservando a representatividade dos dados para as análises subsequentes.

\subsubsection{Impacto da remoção dos pontos influentes}\label{impacto-da-remouxe7uxe3o-dos-pontos-influentes}

\begin{longtable}[]{@{}lrrr@{}}
\caption{\label{tab:comparaCoef} Comparação das estimativas antes e depois da remoção dos pontos influentes.}\tabularnewline
\toprule\noalign{}
Termo & modelo2 (completo) & modelo2 (refinado) & Diferença (\%) \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Termo & modelo2 (completo) & modelo2 (refinado) & Diferença (\%) \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
(Intercept) & 18.466 & 4.019 & -78.23 \\
Murder & 11.972 & 12.020 & 0.40 \\
Rape & 2.782 & 3.315 & 19.18 \\
\end{longtable}

Removendo as 3 observações influentes, o coeficiente de determinação ajustado aumenta de 0.697 para 0.773, e o erro padrão residual diminui de 45.848 para 39.089. As variações nos coeficientes são pequenas, indicando que as observações influentes refletem a variabilidade natural dos dados e não erros de registro. Como a diferença entre as estimativas é reduzida e os pressupostos do modelo já eram atendidos pelo modelo2 completo, optamos por manter todas as observações no modelo final utilizado nas próximas seções, evitando descartar informações relevantes da base \texttt{USArrests}.

\subsection{Interpretações do modelo selecionado}\label{interpretauxe7uxf5es-do-modelo-selecionado}

O modelo2 explica uma proporção estatisticamente significante e substancial da variância da variável resposta \texttt{Assault} (\(R^2\) ajustado \(= 0.697\); \(F(2, 47) = 57.4\), \(p<0{,}001\)). Especificamente:

\begin{itemize}
\item
  para cada aumento de 1 prisão por assassinato (\texttt{Murder}), por 100 mil habitantes, mantendo \texttt{Rape} constante, o número médio esperado de prisões por assalto aumenta em \(11.972\) por 100 mil habitantes;
\item
  para cada aumento de 1 prisão por estupro (\texttt{Rape}), por 100 mil habitantes, mantendo \texttt{Murder} constante, o número médio esperado de prisões por assalto aumenta em \(2.782\) por 100 mil habitantes.
\end{itemize}

Note que ambos os efeitos são positivos e coerentes com a análise de correlação apresentada anteriormente. Além disso, a remoção da variável \texttt{UrbanPop} resultou em um modelo mais simples, sem perda significativa de qualidade do ajuste, confirmando que \texttt{Murder} e \texttt{Rape} são suficientes para explicar a maior parte da variação observada em \texttt{Assault}.

\subsection{Comparação geral dos modelos}\label{comparauxe7uxe3o-geral-dos-modelos}

\subsubsection{Coeficientes padronizados}\label{coeficientes-padronizados}

Embora as variáveis explicativas deste modelo sejam medidas na mesma unidade (prisões por 100 mil habitantes), calculamos os coeficientes padronizados para ilustrar a comparação da importância relativa de cada variável explicativa.

\begin{verbatim}
lm.beta::lm.beta(modelo2)
\end{verbatim}

\begin{verbatim}
## 
## Call:
## lm(formula = Assault ~ Murder + Rape, data = dados)
## 
## Standardized Coefficients::
## (Intercept)      Murder        Rape 
##          NA   0.6256897   0.3126158
\end{verbatim}

Os coeficientes padronizados indicam que \texttt{Murder} (beta padronizado \(\approx 0.63\)) possui maior peso relativo do que \texttt{Rape} (beta padronizado \(\approx 0.31\)) na explicação da variável resposta \texttt{Assault}, uma vez que ambas são comparadas na mesma escala.

\section{Previsões}\label{previsuxf5es}

Para realizar previsões, é recomendável utilizar valores das variáveis explicativas dentro do intervalo observado nos dados (Tabela \ref{tab:descritivas}). Utilizando o modelo2, apresentamos as previsões para dois conjuntos hipotéticos: \(\mathbf{x}_1\), representando um estado com menores taxas de prisões por assassinato (\texttt{Murder\ =\ 5}) e estupro (\texttt{Rape\ =\ 15}); e \(\mathbf{x}_2\), representando um estado com taxas mais elevadas desses crimes (\texttt{Murder\ =\ 15} e \texttt{Rape\ =\ 30}).

\subsection{Intervalo de confiança para o valor médio esperado}\label{intervalo-de-confianuxe7a-para-o-valor-muxe9dio-esperado}

\begin{longtable}[]{@{}rrrrr@{}}
\caption{\label{tab:previsaoConfianca} Intervalos de confiança de 95\% para o número médio esperado de prisões por assalto, para os dois conjuntos hipotéticos.}\tabularnewline
\toprule\noalign{}
Murder & Rape & Estimativa & Limite inferior & Limite superior \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Murder & Rape & Estimativa & Limite inferior & Limite superior \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
5 & 15 & 120.05 & 103.77 & 136.32 \\
15 & 30 & 281.49 & 256.07 & 306.91 \\
\end{longtable}

\textbf{Interpretação prática}: para um estado com taxa de \texttt{Murder\ =\ 5} e \texttt{Rape\ =\ 15} (por 100 mil habitantes), estimamos que o número \textbf{médio} de prisões por assalto esteja entre 103.77 e 136.32 por 100 mil habitantes, com 95\% de confiança. Já para um estado com \texttt{Murder\ =\ 15} e \texttt{Rape\ =\ 30}, o número médio esperado de prisões por assalto está entre 256.07 e 306.91 por 100 mil habitantes.

\subsection{Intervalo de predição para uma nova observação}\label{intervalo-de-prediuxe7uxe3o-para-uma-nova-observauxe7uxe3o}

\begin{longtable}[]{@{}rrrrr@{}}
\caption{\label{tab:previsaoPredicao} Intervalos de predição de 95\% para uma nova observação da variável \protect\texttt{Assault}, para os dois conjuntos hipotéticos.}\tabularnewline
\toprule\noalign{}
Murder & Rape & Estimativa & Limite inferior & Limite superior \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Murder & Rape & Estimativa & Limite inferior & Limite superior \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
5 & 15 & 120.05 & 26.39 & 213.71 \\
15 & 30 & 281.49 & 185.82 & 377.16 \\
\end{longtable}

\textbf{Interpretação prática}: se observarmos \textbf{um único novo estado} com taxas de \texttt{Murder\ =\ 5} e \texttt{Rape\ =\ 15} (por 100 mil habitantes), prevemos, com 95\% de confiança, que a taxa de prisões por assalto estará entre 26.39 e 213.71 por 100 mil habitantes. Este intervalo é mais largo do que o intervalo de confiança para a média, pois considera, além da incerteza da estimativa média, a variabilidade natural entre os estados. Da mesma forma, para um novo estado com \texttt{Murder\ =\ 15} e \texttt{Rape\ =\ 30}, a taxa prevista de prisões por assalto estará entre 185.82 e 377.16 por 100 mil habitantes.

Em ambos os casos, a estimativa pontual (120.05 e 281.49 prisões por 100 mil habitantes) permanece a mesma dos intervalos de confiança. A diferença está apenas na largura dos intervalos, refletindo a distinção entre estimar a média da população e prever o valor de uma única observação. Por esse motivo, o intervalo de predição é sempre mais amplo e deve ser utilizado quando o interesse é prever o comportamento de um estado específico.

\section{Conclusão}\label{conclusuxe3o}

A análise exploratória indicou associação positiva entre a variável resposta \texttt{Assault} e as variáveis \texttt{Murder} e \texttt{Rape}, enquanto \texttt{UrbanPop} apresentou relação mais fraca com as demais variáveis. O modelo inicial, contendo todas as variáveis explicativas, apresentou bom ajuste (\(R^2\) ajustado \(= 0.701\)), sem evidências de multicolinearidade severa, uma vez que todos os valores de VIF permaneceram abaixo dos limites de referência.

O modelo final selecionado, composto pelas variáveis \texttt{Murder} e \texttt{Rape}, preservou praticamente o mesmo poder explicativo do modelo completo (perda de apenas 0.4 pontos percentuais no \(R^2\) ajustado) e apresentou valores menores de AIC e BIC, resultando em um modelo mais simples e parcimonioso. Seus pressupostos foram verificados por meio da análise dos resíduos e do gráfico de envelope simulado, e a avaliação dos pontos influentes mostrou que sua remoção não altera de forma relevante as estimativas do modelo.

Por fim, foram obtidos intervalos de confiança para o valor médio esperado e intervalos de predição para novas observações, evidenciando a diferença entre estimar a média da resposta e prever o comportamento de um estado específico. Dessa forma, o modelo selecionado mostrou-se adequado para explicar a variação da taxa de prisões por assalto a partir das taxas de prisões por assassinato e estupro, atendendo aos objetivos propostos neste trabalho.







\bibliographystyle{RS}
\bibliography{modeloUFCG.bib}


\end{document}
